### ISSUE TITLE
Ustalenie wystawianego api

### ISSUE THREAD

**Issue by arkadiuszpasek** [bohatiuk/twitter-stash#6]

**Comment by arkadiuszpasek** [comment]
@bohatiuk @Eugenija1 @kamilr123
tak po syncach i z którejś zasady dynamiki newtona o pracy grupowej możliwe, że kieruje do Antona, ale nie wiem jak się podzielicie z backendem C:

To tak, żeby zrobić coś w stylu tych mock-upów co tam posklejałem
 - endpoint do listy tweetów
   - np. `/api/tweets` - zwracający listę tweetów
     - zwraca ograniczoną ilość tweetów i teraz mi obojętne czy to będzie zrobione przez np. query params typu ?offset=N&limit&N, czy przez `/api/tweets/page/1` - zwracający z góry narzuconą z odpowiednim przesunięciem
 - do grupowania, np. będziemy grupować po autorach
   - więc endpoint typu `/api/authors` - zależnie od ilości też może być limit tego ile jest zwracane
   - jeśli będziemy mieć kategorie to podobnie - niżej komentarz

i żeby wyświetlić listę dot. tylko jakieś autora, najłatwiej chyba po prostu opcjonalne parametry podpiąć do endpointa np. `api/tweets?author="John%20Doe"`

edit: a w zasadzie co do linijki wyżej, user prawdopodobnie ma swój unique userName, więc bardziej `api/tweets?author="elonmusk"`, żeby znaleźć tweety `@elonmusk`

**Comment by arkadiuszpasek** [comment]
Zwracamy jsona, zakładam, że będzie zawarte coś w stylu
```
interface Tweet {
 publicationTimestamp: number;
 content: string;
 author: Author
}

interface Author {
  name: string;
  userName: string;
  jakby się dało to avatarUrl?: string albo coś
}
```
Struktura co dokładnie zawiera do ustalenia z tym co będziemy mieć w bazie

**Comment by arkadiuszpasek** [comment]
Tu się jeszcze muszę zastanowić jak np. na froncie będziemy mieć agregację po autorze i subreddicie np., jak to pobierać do jakiegoś autocompleta, bo to będzie dużo danych, być może trzeba będzie dodać na endpoinice /authors, query param, który będzie czymś w stylu regexa (będzie sprawdzał które się z tym parametrem zgadza i tylko takich zwracał, żeby to jakoś ograniczyć)

**Comment by bohatiuk** [comment]
Tu kontynujemy issue "Analiza tweetów - część 1 #8"

**Comment by bohatiuk** [comment]
Arkadiusz Pasek:

Może być jako osobny serwis, bo taka była wola, tylko to też więcej pracy :P

Potrzebujemy serwis, który będzie w stanie mieć endpoint w stylu `/api/analyze/{id}` - gdzie id to id postu w bazie
I robi tam analizy i zwraca wynik np. typu
```typescript
interface Analysis {
  predictedAge: number;
}
```

Część pierwsza, taki core czyli musimy mieć te operacje i musi odpowiadać
Część druga, to co dzisiaj na syncu mówione, czyli jeśli będziemy mieć agregacje np. po grupie wiekowej musi być dodatkowa tabela w bazie

**Comment by bohatiuk** [comment]
@arkadiuszpasek 

API:

1. lista subredditow (defaultowo grupowane po nazwie)
GET /subreddits

Response payload (json):
subreddits: [string]

2. lista wszystkich postow ze strony P (do ustalenia ilsoc postow per strone)
GET /posts?page=P

Response payload (json):
posts: 	      
```
                        [{"post_id": int, 
			"author": string}
			"score": int,
			"title": string,
			"subreddit": string,
			"body": string,
			"num_comments": int,
			"created": timestamp]
```
2.a [opcjonalnie]
podanie z ktorego subreddita wybierac posty
GET /posts?page=P&[subreddit=S]
2.b [opcjonalnie]
podanie opcji grupowania
GET /posts?page=P&[subreddit=S]&[groupby=T]

```
enum T {
	time,
	author,
	num_comments,
	score
}
```
2.c [opcjonalnie]
podanie tylko postow dla okreslonego autora
GET /posts?page=P&[subreddit=S]&[groupby=T]&[author=A]
3.  predykcja grupy wiekowej
GET /label/age?author=A

Response payload (json):
subreddits: {label: int}
4. predykcja sentymentu
GET /label/sentiment?author=A

Response payload (json):
subreddits: {label: string}

**Comment by bohatiuk** [comment]
closing, api settled
