### ISSUE TITLE
Analiza tweetów - część 1

### ISSUE THREAD

**Issue by arkadiuszpasek** [bohatiuk/twitter-stash#8]
Może być jako osobny serwis, bo taka była wola, tylko to też więcej pracy :P

Potrzebujemy serwis, który będzie w stanie mieć endpoint w stylu `/api/analyze/{id}` - gdzie id to id postu w bazie
I robi tam analizy i zwraca wynik np. typu
```typescript
interface Analysis {
  predictedAge: number;
}
```

Część pierwsza, taki core czyli musimy mieć te operacje i musi odpowiadać
Część druga, to co dzisiaj na syncu mówione, czyli jeśli będziemy mieć agregacje np. po grupie wiekowej musi być dodatkowa tabela w bazie

**Comment by bohatiuk** [comment]
Post jest indeksowany poprzez id bazy i id rzeczywiste redditowe. Dodatkowo zrobimy federacje api w gateway-ju, wiec nie musisz dla poszczegolnego serwisu tworzyc wymagania co do api. Tak naprawde lepiej jak bys dodawal wymagania co do funkcjonalnosci, a wymagania co do api dodawac do serwsisu ktory stworze, czyli api gateway

**Comment by arkadiuszpasek** [comment]
Tak, nic co jest napisane wyżej nie jest wymaganiem tylko luźnym przykładem żeby zobrazować o co chodzi, ja wymagań żadnych nie narzucam co do tego jak będzie komunikacja na backendzie wyglądać, zakładam, że będzie w stanie api gateway odpowiedzieć na zapytanie o tweet z analizą

**Comment by arkadiuszpasek** [comment]
@bohatiuk 
W sumie możesz doprecyzować tego taska, bo widzę, że stworzyłeś też następnego z inną analizą a ja nie jestem pewny jak to ma być podzielone (w sensie co gdzie się analizuje),

**Comment by bohatiuk** [comment]
Issue zmergowane do "Ustalenie wystawianego api #6"
